spring:
  datasource:
    driver-class-name:
      com.mysql.cj.jdbc.Driver
    url:
      jdbc:mysql://localhost:43306/onlineJudge?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username:
      root
    password:
      root
  config:
    name:
      mybatisplus, server
  mvc:
    view:
      prefix: /
      suffix: .jsp


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:com/example/onlinejudge/mapper/*.xml

server:
  port: 8083



